HuntTransaction.reward_contributor!('teamhumble', 30000, 1, 'contribution', 'Contibution on promoting Steemhunt Project')
HuntTransaction.reward_contributor!('superoo7', 3000, 1, 'contribution', 'Contibution on Development')
HuntTransaction.reward_contributor!('monajam', 2000, 1, 'contribution', 'Contribution on Discord Channel')

HuntTransaction.reward_contributor!('geekgirl', 2000, 1, 'contribution', 'Contribution on Discord Channel')
HuntTransaction.reward_contributor!('jayplayco', 10000, 1, 'contribution', 'Contibution on promoting Steemhunt Project')
HuntTransaction.reward_contributor!('blogiwank', 5000, 1, 'contribution', 'Local Language Contributions - Indonesian')
HuntTransaction.reward_contributor!('dayleeo', 2000, 1, 'contribution', 'PG visualization')
HuntTransaction.reward_contributor!('moneyhacks', 2000, 1, 'contribution', 'Contibution on promoting Steemhunt Project')
HuntTransaction.reward_contributor!('joythewanderer', 2000, 1, 'contribution', 'Local Language Contributions - Chinese')
HuntTransaction.reward_contributor!('catwomanteresa', 2000, 1, 'contribution', 'Local Language Contributions - Chinese')
HuntTransaction.reward_contributor!('lpessin', 1000, 1, 'contribution', 'Local Language Contributions - Portuguese')
HuntTransaction.reward_contributor!('charincharin', 2000, 1, 'contribution', 'Local Language Contributions - Japanese')
HuntTransaction.reward_contributor!('espoem', 5000, 1, 'contribution', 'Contribution on Discord Channel')
HuntTransaction.reward_contributor!('exyle', 10000, 1, 'contribution', 'Contibution on promoting Steemhunt Project')
HuntTransaction.reward_contributor!('verhp11', 3000, 1, 'contribution', 'Contibution on promoting Steemhunt Project')
HuntTransaction.reward_contributor!('taskmaster4450', 5000, 1, 'contribution', 'Contibution on promoting Steemhunt Project')
HuntTransaction.reward_contributor!('kevinwong', 5000, 1, 'contribution', 'Contibution on promoting Steemhunt Project')
HuntTransaction.reward_contributor!('meditateonthat', 1500, 1, 'contribution', 'Contribution on Discord Channel')

HuntTransaction.reward_contributor!('teamhumble', 2000, 1,  'moderator', 'Weekly HUNT Tokens for mods')
HuntTransaction.reward_contributor!('fknmayhem', 2000, 1,  'moderator', 'Weekly HUNT Tokens for mods')
HuntTransaction.reward_contributor!('folken', 2000, 1,  'moderator', 'Weekly HUNT Tokens for mods')
HuntTransaction.reward_contributor!('dayleeo', 2000, 1,  'moderator', 'Weekly HUNT Tokens for mods')
HuntTransaction.reward_contributor!('jayplayco', 2000, 1,  'moderator', 'Weekly HUNT Tokens for mods')
HuntTransaction.reward_contributor!('urbangladiator', 2000, 1,  'moderator', 'Weekly HUNT Tokens for mods')
HuntTransaction.reward_contributor!('chronocrypto', 2000, 1,  'moderator', 'Weekly HUNT Tokens for mods')
HuntTransaction.reward_contributor!('joannewong', 2000, 1,  'moderator', 'Weekly HUNT Tokens for mods')
HuntTransaction.reward_contributor!('bitrocker2020', 2000, 1,  'moderator', 'Weekly HUNT Tokens for mods')

HuntTransaction.reward_contributor!('fknmayhem', 6000, 1, 'guardian', 'Weekly HUNT Tokens for Guardian')
HuntTransaction.reward_contributor!('folken', 6000, 1, 'guardian', 'Weekly HUNT Tokens for Guardian')
